# Generated by Django 5.0.3 on 2024-03-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
