# Generated by Django 5.0.3 on 2024-04-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_feedback_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['user_telegram_id'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='user_telegram_id',
        ),
    ]
