# Generated by Django 5.0.3 on 2024-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_botuser_last_name_alter_botuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='telegram_id',
            field=models.PositiveBigIntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
