# Generated by Django 5.0.3 on 2024-05-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_spots_average_rating_alter_evaluation_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_code', models.CharField(verbose_name='Icon code')),
                ('icon_image', models.ImageField(upload_to='', verbose_name='Icon image')),
            ],
            options={
                'verbose_name': 'Weather icon',
                'verbose_name_plural': 'Weather icons',
            },
        ),
    ]
