# Generated by Django 5.0.3 on 2024-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_weathericons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathericons',
            name='icon_image',
            field=models.ImageField(upload_to='photos/weather/%Y/%m/%d/'),
        ),
    ]
